/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2020-12-17

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/**
  * Original Source Link : http://www.lcdwiki.com/1.3inch_IIC_OLED_Module_SKU:MC130VX,
  *                        1.3inch IIC_OLED Module Package
  *                        \1-Demo\Demo_STM32\Demo_OLED_STM32F103RCT6_Software_IIC
  * Library      : SPL
  * Target board : STM32-BSKO Board
  * I2C SDA PB15 --> PB11
  * I2C SCL PB13 --> PB10
  *
  */

/* Includes */
#include <stddef.h>
#include "stm32f10x.h"

/* Porting includes*/
#include "delay.h"
#include "sys.h"
#include "oled.h"
#include "gui.h"
#include "test.h"

/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{

    delay_init();
    NVIC_Configuration();
    OLED_Init();
    OLED_Clear(0);

  while (1)
  {
      TEST_MainPage();         //Display main interface
      OLED_Clear(0);
      Test_Color();            //Update display
      OLED_Clear(0);
      Test_Rectangular();      //Draw rectangle
      OLED_Clear(0);
      Test_Circle();           //Draw circle
      OLED_Clear(0);
      Test_Triangle();         //Draw triangle
      OLED_Clear(0);
      TEST_English();          //Display english
      OLED_Clear(0);
      TEST_Number_Character(); //Display number and special characters
      OLED_Clear(0);
      TEST_Chinese();          //Display chinese
      OLED_Clear(0);
      TEST_BMP();              //Display BMP monochrome picture
      OLED_Clear(0);
      TEST_Menu1();            //Display menu1
      OLED_Clear(0);
      TEST_Menu2();            //Display menu1
      OLED_Clear(0);
  }
}


#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}

#ifdef USE_SEE
#ifndef USE_DEFAULT_TIMEOUT_CALLBACK
/**
  * @brief  Basic management of the timeout situation.
  * @param  None.
  * @retval sEE_FAIL.
  */
uint32_t sEE_TIMEOUT_UserCallback(void)
{
  /* Return with error code */
  return sEE_FAIL;
}
#endif
#endif /* USE_SEE */

